apiVersion: apps/v1
kind: Deployment
metadata:
  name: benchmark-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: benchmark-example
  template:
    metadata:
      labels:
        app: benchmark-example
    spec:
      containers:
        - name: benchmark-example
          image: greptime-registry.cn-hangzhou.cr.aliyuncs.com/tools/benchmark_example:weny-2025-0610-02
          imagePullPolicy: IfNotPresent
          command:
            - "java"
            - "-Dtarget=metrics"
            - "-Dzstd_compression=false"
            - "-Dbatch_size_per_request=500"
            - "-Dconcurrency=4"
            - "-jar"
            - "/app/benchmark_example.jar"
          resources:
            requests:
              cpu: 1
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "8Gi"
              
