name: Build JAR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: ./build-fat-jar.sh

    - uses: actions/upload-artifact@v4
      with:
        path: ./target/benchmark_example.jar

    - name: Login to Aliyun ACR
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 1
        max_attempts: 10
        retry_on: any
        command: docker login --username='${{ secrets.ALICLOUD_USERNAME }}' --password='${{ secrets.ALICLOUD_PASSWORD }}' greptime-registry.cn-hangzhou.cr.aliyuncs.com

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: latest
